version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ope
    main: .
    binary: ope
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - id: ope-windows
    main: .
    binary: ope
    ldflags:
      - -s -w -X main.Version={{.Version}} -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

universal_binaries:
  - id: ope-universal
    ids:
      - ope
    replace: true
    name_template: ope

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "ope_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
